package po;

// Generated 2015-7-4 19:12:24 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Dept generated by hbm2java
 */
@Entity
@Table(name = "dept", catalog = "meeting")
public class Dept implements java.io.Serializable {

	private int did;
	private String dname;

	private Set<Emp> set = new HashSet<Emp>();
	public Dept() {
	}

	public Dept(String dname) {
		this.dname = dname;
	}

	
	public Dept(int did, String dname) {
		super();
		this.did = did;
		this.dname = dname;
	}

	public Dept(int did) {
		super();
		this.did = did;
	}

	@Id
	@Column(name = "did", unique = true, nullable = false)
	public int getDid() {
		return this.did;
	}

	public void setDid(int did) {
		this.did = did;
	}

	@Column(name = "dname", length = 20)
	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	@OneToMany(fetch = FetchType.LAZY,  targetEntity = Emp.class, mappedBy = "dept")
	public Set<Emp> getSet() {
		return set;
	}

	public void setSet(Set<Emp> set) {
		this.set = set;
	}
}
