package po;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;
import org.hibernate.service.ServiceRegistryBuilder;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "meeting")
public class Emp implements java.io.Serializable {

	private int eid;
	private String names;
	private String ename;
	private String epasswd;
	private String ephone;
	private String email;
	private int s_privilege;
	private Dept dept=new Dept();

	@Id
	@Column(name = "eid", unique = true, nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "names", length = 30)
	public String getNames() {
		return names;
	}

	public Emp(String names, String ename, String epasswd, String ephone,
			String email) {
		super();
		this.names = names;
		this.ename = ename;
		this.epasswd = epasswd;
		this.ephone = ephone;
		this.email = email;
	}

	public void setNames(String names) {
		this.names = names;
	}

	
	@Column(name = "ename", length = 30)
	public String getEname() {
		return this.ename;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	@Column(name = "epasswd", length = 20)
	public String getEpasswd() {
		return epasswd;
	}

	public void setEpasswd(String epasswd) {
		this.epasswd = epasswd;
	}

	@Column(name = "ephone", length = 20)
	public String getEphone() {
		return ephone;
	}

	public void setEphone(String ephone) {
		this.ephone = ephone;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "s_privilege" )
	public int getS_privilege() {
		return s_privilege;
	}

	public void setS_privilege(int s_privilege) {
		this.s_privilege = s_privilege;
	}
	
	//查询时会把关联的对象全部加载到内存中
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "did")
	public Dept getDept() {
		return dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}
	
	public Emp() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Emp(int eid, String names, String ename, String epasswd,
			String ephone, String email, int s_privilege, Dept dept) {
		super();
		this.eid = eid;
		this.names = names;
		this.ename = ename;
		this.epasswd = epasswd;
		this.ephone = ephone;
		this.email = email;
		this.s_privilege = s_privilege;
		this.dept = dept;
	}

	
}
