package po;

// Generated 2015-7-10 15:44:41 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Meet generated by hbm2java
 */
@Entity
@Table(name = "meet", catalog = "meeting")
public class Meet implements java.io.Serializable {

	private String mname;
	private Emp emp;
	private Room room;
	private Integer mnumber;
	private Date mstarttime;
	private Date mendtime;
	private Date appointtime;
	private String mremark;
	private String memps;
	private Integer mstate;
	private String cancelreason;

	public String getCancelreason() {
		return cancelreason;
	}

	@Override
	public String toString() {
		return "Meet [mname=" + mname + ", mnumber=" + mnumber
				+ ", mstarttime=" + mstarttime + ", mendtime=" + mendtime
				+ ", appointtime=" + appointtime + ", mremark=" + mremark
				+ ", memps=" + memps + ", mstate=" + mstate + ", cancelreason="
				+ cancelreason + "]";
	}

	public void setCancelreason(String cancelreason) {
		this.cancelreason = cancelreason;
	}

	public Meet() {
	}

	public Meet(String mname, Date mstarttime, Date mendtime, Date appointtime) {
		this.mname = mname;
		this.mstarttime = mstarttime;
		this.mendtime = mendtime;
		this.appointtime = appointtime;
	}

	public Meet(String mname, Emp emp, Room room, Integer mnumber,
			Date mstarttime, Date mendtime, Date appointtime, String mremark,
			String memps, Integer mstate) {
		this.mname = mname;
		this.emp = emp;
		this.room = room;
		this.mnumber = mnumber;
		this.mstarttime = mstarttime;
		this.mendtime = mendtime;
		this.appointtime = appointtime;
		this.mremark = mremark;
		this.memps = memps;
		this.mstate = mstate;
	}

	@Id
	@Column(name = "mname", unique = true, nullable = false, length = 20)
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "appointmentid")
	public Emp getEmp() {
		return this.emp;
	}

	public void setEmp(Emp emp) {
		this.emp = emp;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "rid")
	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	@Column(name = "mnumber")
	public Integer getMnumber() {
		return this.mnumber;
	}

	public void setMnumber(Integer mnumber) {
		this.mnumber = mnumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mstarttime", nullable = false, length = 19)
	public Date getMstarttime() {
		return this.mstarttime;
	}

	public void setMstarttime(Date mstarttime) {
		this.mstarttime = mstarttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "mendtime", nullable = false, length = 19)
	public Date getMendtime() {
		return this.mendtime;
	}

	public void setMendtime(Date mendtime) {
		this.mendtime = mendtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "appointtime", nullable = false, length = 19)
	public Date getAppointtime() {
		return this.appointtime;
	}

	public void setAppointtime(Date appointtime) {
		this.appointtime = appointtime;
	}

	@Column(name = "mremark", length = 50)
	public String getMremark() {
		return this.mremark;
	}

	public void setMremark(String mremark) {
		this.mremark = mremark;
	}

	@Column(name = "memps", length = 100)
	public String getMemps() {
		return this.memps;
	}

	public void setMemps(String memps) {
		this.memps = memps;
	}

	@Column(name = "mstate")
	public Integer getMstate() {
		return this.mstate;
	}

	public void setMstate(Integer mstate) {
		this.mstate = mstate;
	}

}
